### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EzequielCardone** [purrplingcat/NpcAdventures#170]
**Describe the bug**
I cannot add the mod to the game

**To Reproduce**
I simply start the game. 

**Expected behavior**
The mod is added without issue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SDV version: 1.5.4 (Steam version)
 - SMAPI version: 3.10.1
 - Version: 0.16.1

**Additional context**
Clean Stardew installation. I downloaded all the required mods on the same day, have SMAPI installed correctly. All my other mods are loaded correctly except for this one.

SMAPI's log:

[SMAPI]       These mods could not be added to your game.
[SMAPI]       - NPC Adventures 0.16.1 because initialization failed:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at StardewModdingAPI.Framework.SCore.TryLoadModEntry(Assembly modAssembly, Mod& mod, String& error) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1742
   at StardewModdingAPI.Framework.SCore.TryLoadMod(IModMetadata mod, IModMetadata[] mods, AssemblyLoader assemblyLoader, InterfaceProxyFactory proxyFactory, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase, HashSet`1 suppressUpdateChecks, Nullable`1& failReason, String& errorReasonPhrase, String& errorDetails) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1668
Failed loading type 'QuestFramework.Quests.IQuestInfoUpdater': System.TypeLoadException: Could not load type 'QuestFramework.Quests.IQuestInfoUpdater' from assembly 'QuestFramework, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null'.

Quest framework version: 1.3.4

**Comment by purrplingcat** [comment]
Download amd install QF 1.4, NA requires it.
